### PR TITLE
UI Complete!

### LINKED ISSUE #2: UI and Contents
@psh2849 @seoh02h @sunnnl 
I'm designing an app.
There are four things we decided to put on our business cards.
1. name
2. tel
3. e-mail
4. company

I searched for 'business cards' on Google, but they seem to use addresses mostly. 

image

How about changing company to **address** ?

### PR DESCRIPTION
**Pull request by Jsueeee**

### CODE REVIEW

**Comment by Jsueeee** [comment]
@psh2849 @sunnnl @seoh02h 
Please review the contents!

**Comment by sunnnl** [comment]
Seriously?
It's a really cool design !

I have a question about size of patch.
It's a bit difficult to check and review all codes at the beginning of a project.
I wonder about the amount of patch for init setting in general.
@designe @yeonns

**Comment by psh2849** [comment]
It's great!
After confirming the feedback, I will do next step

**Comment by seohy02** [comment]
Amazing..... （⊙ｏ⊙）

**Comment by yeonns** [comment]
> Seriously?
> It's a really cool design !
> 
> I have a question about size of patch.
> It's a bit difficult to check and review all codes at the beginning of a project.
> I wonder about the amount of patch for init setting in general.
> @designe @yeonns

@sunnnl 
It's a good idea to consider patch size for code review! 👍 
There's no perfect guideline for patch size, but below article says optimal pull request size. (1 PR <= 200 lines)
https://smallbusinessprogramming.com/optimal-pull-request-size/

PR size is important, but I think the commit size is more important.
This is because we can do code review by commit in ```Files changed``` like below picture.
image

So, try to configure the commit size as small as possible for efficient code review. 
For example, your first commit is 
- Add Activities : MainActivity, MakeCardFragment, CardBoxFragment

It can be divided with 4 commits like this:
- Add MainActivity
- Add MakeCardFragment
- Add CardBoxFragment
- Link MainActivity with MakeCardFragment and CardBoxFragment

**Comment by sunnnl** [comment]
@yeonns 
Thanks for answer :)

**Comment by designe** [comment]
@sunnnl are you UI designer?!
Awesome!!
I was surprised at how cool it was.

**Comment by sunnnl** [comment]
> @sunnnl are you UI designer?!
> Awesome!!
> I was surprised at how cool it was.

Umm .. you mean @Jsueeee ? :) 
I agree ! Her design is super cool

**Comment by designe** [comment]
> > @sunnnl are you UI designer?!
> > Awesome!!
> > I was surprised at how cool it was.
> 
> Umm .. you mean @Jsueeee ? :)
> I agree ! Her design is super cool

HaHa, Sorry 😢 
@Jsueeee
You have outstanding sense for UI Design :)

**Comment by Jsueeee** [comment]
> > > @sunnnl are you UI designer?!
> > > Awesome!!
> > > I was surprised at how cool it was.
> > 
> > 
> > Umm .. you mean @Jsueeee ? :)
> > I agree ! Her design is super cool
> 
> HaHa, Sorry 😢
> @Jsueeee
> You have outstanding sense for UI Design :)

Oh, Thank you very much!!!! 😁

**Pull request merged**
